## Flow model {#modelFlow}

```{r globalModelsFlow, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```


```{r librariesModelsFlow, echo = FALSE}
library(getWBData)
library(tidyverse)
library(lubridate)
library(kableExtra)
library(GGally)
library(lme4)
```

```{r readInFlowData}
dataFlow <- read.csv("./dataIn/wbFlow/EcoDrought_Continuous_MA.csv")
```

```{r filterDataFlow}
tibble(dataFlow)
table(dataFlow$Site_Name)

d <- dataFlow %>%
  filter(Site_Name %in% c("Jimmy Brook", "Mitchell Brook", "Obear Brook Lower", "West Brook 0")) %>%
  mutate(date = mdy_hm(DateTime_EST),
         site = recode(Site_Name, "Jimmy Brook" = "OL", "Mitchell Brook" = "OS", "Obear Brook Lower" = "IS", "West Brook 0" = "WB"),
         dischargeLog = log(Discharge_Hobo_cfs + 0.01))
  
  
d %>% filter(is.infinite(dischargeLog))

scaleCol <- function(d){
  return (d - mean(d, na.rm = TRUE)) / sd(d, na.rm = TRUE)
}
# hard-coded for now
dWide <- d %>% 
  pivot_wider(id_cols = date, 
              values_from = dischargeLog, 
              names_from = site
             ) %>%
  mutate(
         OLScaled = scaleCol(OL),
         ISScaled = scaleCol(IS),
         OSScaled = scaleCol(OS),
         WBScaled = scaleCol(WB),
         yday = yday(date),
         year = year(date)
        )



```

```{r flowPlots, cache = TRUE}

ggplot(d, aes(date, dischargeLog, color = Site_Name)) +
  geom_point(size = 0.02) +
  facet_wrap(~Site_Name)

ggpairs(dWide,
          columns = 6:9,
          mapping = ggplot2::aes(color = as.factor(year), alpha = 0.7),
          #diag = list(continuous = myDens),
          lower = list(continuous = wrap("points", alpha = 0.3, size=0.1), 
                       combo = wrap("dot", alpha = 0.4, size=0.2))
        )

ggpairs(dWide %>% filter(yday > 90, yday < 300),
          columns = 6:9,
          mapping = ggplot2::aes(color = as.factor(year)),
          lower = list(continuous = wrap("points", alpha = 0.3, size=0.1), 
                       combo = wrap("dot", alpha = 0.4, size=0.2))
        )

ggpairs(dWide %>% filter(yday == 110),
          columns = 8:11,
          mapping = ggplot2::aes(color = as.factor(year)),
          lower = list(continuous = wrap("points", alpha = 0.3, size=0.2), 
                       combo = wrap("dot", alpha = 0.4, size=0.2))
        )
```

```{r flowModels}

#mod0 <- lmer(OL ~ WB * yday + as.factor(year) + 1|yday, data = dWide)

```

